// Code generated by protoc-gen-go.
// source: organisations.proto
// DO NOT EDIT!

/*
Package organisations is a generated protocol buffer package.

It is generated from these files:
	organisations.proto

It has these top-level messages:
	Organisation
*/
package organisations

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Organisation struct {
	// @inject_tag: jsonapi:"primary,organisation"
	ID string `protobuf:"bytes,1,opt,name=ID" json:"ID,omitempty" jsonapi:"primary,organisation"`
	// @inject_tag: jsonapi:"attr,displayName"
	DisplayName string `protobuf:"bytes,2,opt,name=displayName" json:"displayName,omitempty" jsonapi:"attr,displayName"`
	// @inject_tag: jsonapi:"attr,registeredName"
	RegisteredName string `protobuf:"bytes,3,opt,name=registeredName" json:"registeredName,omitempty" jsonapi:"attr,registeredName"`
	// @inject_tag: jsonapi:"attr,country"
	Country string `protobuf:"bytes,4,opt,name=country" json:"country,omitempty" jsonapi:"attr,country"`
	// @inject_tag: jsonapi:"attr,currency"
	Currency string `protobuf:"bytes,5,opt,name=currency" json:"currency,omitempty" jsonapi:"attr,currency"`
	// @inject_tag: jsonapi:"attr,companyNumber"
	CompanyNumber int64 `protobuf:"varint,6,opt,name=companyNumber" json:"companyNumber,omitempty" jsonapi:"attr,companyNumber"`
	// @inject_tag: jsonapi:"attr,sageReference"
	SageReference string `protobuf:"bytes,7,opt,name=sageReference" json:"sageReference,omitempty" jsonapi:"attr,sageReference"`
	// @inject_tag: jsonapi:"attr,brandHexColor"
	BrandHexColor string `protobuf:"bytes,8,opt,name=brandHexColor" json:"brandHexColor,omitempty" jsonapi:"attr,brandHexColor"`
	// @inject_tag: jsonapi:"attr,brandLogoId"
	BrandLogoID string `protobuf:"bytes,9,opt,name=brandLogoID" json:"brandLogoID,omitempty" jsonapi:"attr,brandLogoId"`
	// @inject_tag: jsonapi:"attr,role"
	Role string `protobuf:"bytes,10,opt,name=role" json:"role,omitempty" jsonapi:"attr,role"`
	// @inject_tag: jsonapi:"attr,managerId"
	ManagerID string `protobuf:"bytes,11,opt,name=managerID" json:"managerID,omitempty" jsonapi:"attr,managerId"`
}

func (m *Organisation) Reset()                    { *m = Organisation{} }
func (m *Organisation) String() string            { return proto.CompactTextString(m) }
func (*Organisation) ProtoMessage()               {}
func (*Organisation) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *Organisation) GetID() string {
	if m != nil {
		return m.ID
	}
	return ""
}

func (m *Organisation) GetDisplayName() string {
	if m != nil {
		return m.DisplayName
	}
	return ""
}

func (m *Organisation) GetRegisteredName() string {
	if m != nil {
		return m.RegisteredName
	}
	return ""
}

func (m *Organisation) GetCountry() string {
	if m != nil {
		return m.Country
	}
	return ""
}

func (m *Organisation) GetCurrency() string {
	if m != nil {
		return m.Currency
	}
	return ""
}

func (m *Organisation) GetCompanyNumber() int64 {
	if m != nil {
		return m.CompanyNumber
	}
	return 0
}

func (m *Organisation) GetSageReference() string {
	if m != nil {
		return m.SageReference
	}
	return ""
}

func (m *Organisation) GetBrandHexColor() string {
	if m != nil {
		return m.BrandHexColor
	}
	return ""
}

func (m *Organisation) GetBrandLogoID() string {
	if m != nil {
		return m.BrandLogoID
	}
	return ""
}

func (m *Organisation) GetRole() string {
	if m != nil {
		return m.Role
	}
	return ""
}

func (m *Organisation) GetManagerID() string {
	if m != nil {
		return m.ManagerID
	}
	return ""
}

func init() {
	proto.RegisterType((*Organisation)(nil), "organisations.Organisation")
}

func init() { proto.RegisterFile("organisations.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 293 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x5c, 0xd1, 0xcf, 0x4a, 0xc3, 0x40,
	0x10, 0x06, 0x70, 0x9a, 0xd6, 0xfe, 0xd9, 0xda, 0x1e, 0xd6, 0xcb, 0x22, 0x1e, 0x8a, 0x88, 0xf4,
	0xd2, 0xe6, 0xe0, 0x51, 0xbc, 0x68, 0x0e, 0x06, 0xa4, 0x42, 0x8f, 0xde, 0x36, 0xc9, 0xb8, 0x0d,
	0x64, 0x77, 0x96, 0xc9, 0x06, 0x9a, 0xf7, 0xf5, 0x41, 0x24, 0x53, 0xd4, 0xc6, 0x5b, 0xe6, 0xf7,
	0x7d, 0x59, 0x18, 0x46, 0x5c, 0x21, 0x19, 0xed, 0xca, 0x5a, 0x87, 0x12, 0x5d, 0xbd, 0xf5, 0x84,
	0x01, 0xe5, 0xa2, 0x87, 0xb7, 0x5f, 0x91, 0xb8, 0x7c, 0x3f, 0x13, 0xb9, 0x14, 0x51, 0x9a, 0xa8,
	0xc1, 0x6a, 0xb0, 0x9e, 0xed, 0xa3, 0x34, 0x91, 0x2b, 0x31, 0x2f, 0xca, 0xda, 0x57, 0xba, 0xdd,
	0x69, 0x0b, 0x2a, 0xe2, 0xe0, 0x9c, 0xe4, 0xbd, 0x58, 0x12, 0x98, 0xb2, 0x0e, 0x40, 0x50, 0x70,
	0x69, 0xc8, 0xa5, 0x7f, 0x2a, 0x95, 0x98, 0xe4, 0xd8, 0xb8, 0x40, 0xad, 0x1a, 0x71, 0xe1, 0x67,
	0x94, 0xd7, 0x62, 0x9a, 0x37, 0x44, 0xe0, 0xf2, 0x56, 0x5d, 0x70, 0xf4, 0x3b, 0xcb, 0x3b, 0xb1,
	0xc8, 0xd1, 0x7a, 0xed, 0xda, 0x5d, 0x63, 0x33, 0x20, 0x35, 0x5e, 0x0d, 0xd6, 0xc3, 0x7d, 0x1f,
	0xbb, 0x56, 0xad, 0x0d, 0xec, 0xe1, 0x13, 0xba, 0xdf, 0x40, 0x4d, 0xf8, 0x99, 0x3e, 0x76, 0xad,
	0x8c, 0xb4, 0x2b, 0x5e, 0xe1, 0xf8, 0x82, 0x15, 0x92, 0x9a, 0x9e, 0x5a, 0x3d, 0xec, 0x36, 0x66,
	0x78, 0x43, 0x83, 0x69, 0xa2, 0x66, 0xa7, 0x8d, 0xcf, 0x48, 0x4a, 0x31, 0x22, 0xac, 0x40, 0x09,
	0x8e, 0xf8, 0x5b, 0xde, 0x88, 0x99, 0xd5, 0x4e, 0x1b, 0xa0, 0x34, 0x51, 0x73, 0x0e, 0xfe, 0xe0,
	0xf9, 0xe9, 0xe3, 0xd1, 0x94, 0xe1, 0xd0, 0x64, 0xdb, 0x1c, 0x6d, 0x5c, 0x11, 0x16, 0x07, 0x6d,
	0x63, 0x43, 0x3e, 0xdf, 0x1c, 0x42, 0xf0, 0x1b, 0x38, 0x6a, 0xeb, 0x2b, 0x88, 0xf9, 0x46, 0x1b,
	0x83, 0x71, 0xef, 0x4a, 0xd9, 0x98, 0xfd, 0xe1, 0x3b, 0x00, 0x00, 0xff, 0xff, 0xb6, 0x6c, 0x5e,
	0xd4, 0xd2, 0x01, 0x00, 0x00,
}
